### ISSUE TITLE
Add support for ffq download scripts

### ISSUE THREAD

**Issue by jfy133** [SPAAM-community/AMDirT#103]
https://github.com/pachterlab/ffq

Similar to CURL etc. but with the accession number.

**Comment by alexhbnr** [comment]
I am not sure how `ffq` will help compared to using our recent approach because `ffq` also just retrieves the metadata and one is required to run `curl` afterwards. See [here](https://github.com/pachterlab/ffq#downloading-data).

**Comment by jfy133** [comment]
Fair point. I think at the time I thought maybe being able to use the funcky pipe things to pull from aWS might be nice but I think that indeed be too complex.

**Comment by jfy133** [comment]
Fair point. I think at the time I thought maybe being able to use the funcky pipe things to pull from aWS might be nice but I think that indeed be too complex.
