### ISSUE TITLE
Add option to display library information in AMDirT viewer

### ISSUE THREAD

**Issue by alexhbnr** [SPAAM-community/AMDirT#119]
Currently, the AMDirT viewer command just displays the information in the respective sample tables. However, it would enhance its use very much when it could also additionally show selected columns of the library tables at the same time. This would be particularly important if one would like to select samples based on sequencing depth or library layout etc., too.

I know that this is not trivial because joining the two tables won't always be a one-to-one join but could also lead to a one-to-many join. However, I think it would be still worth it.

**Comment by jfy133** [comment]
I was also thinking about this and originally my thought was just once you selected your samples, it would load the filtered libraries table below the sales table, and you select those for validate.

But #showerthoughts made me then realise that that might not be so UX/UI friendly, trying to fit two maybe tables on one page.

Thinking about it a bit more, the actually fields you would filter for isn't that many and often not so complex (strandedness, damage treatment, Paiement - all have only 2-4 fields).

So instead, why not under the samples table save an optional/collapsable 'advanced options' section, where you can use a [multiselect](https://docs.streamlit.io/library/api-reference/widgets/st.multiselect) or [selectbox](https://docs.streamlit.io/library/api-reference/widgets/st.selectbox)  field for each of the relevant fields you would actually select for.

If you think about it, the fields with most options (polymerase, sequencing platform) I don't think a user would penalise selection for, so it's unlikely they would interact with those anyway (and they did care, they would know more about the details).

So I think with this solution it would be a more compact implementation of the same functionality. The only downside is you maybe can't inspect the table at fine detail until you've downloaded the table... But personally think if one is being that picky they would be doing it with `convert` anyway.

Thoughts @alexhbnr ? I can do a brief sketch outlining what I mean later
