### ISSUE TITLE
Validate sample accession codes using REST APIs

### ISSUE THREAD

**Issue by jfy133** [SPAAM-community/AMDirT#12]
For example, I used the following R code to find PRJ codes for all ENA/SRA sample accessions.

```
library(tidyverse)
library(jsonlite)
library(httr)
library(xml2)

find_project_accession <- function(accession){
  sample_res <- paste0("https://www.ebi.ac.uk/ena/browser/api/xml/", accession, "?download=false&gzip=false") %>% GET(url = .) %>% content %>% as_list
  secondary_proj_id <- sample_res$SAMPLE_SET$SAMPLE$SAMPLE_LINKS$SAMPLE_LINK$XREF_LINK$ID[[1]]
  secondary_res <- paste0("https://www.ebi.ac.uk/ena/browser/api/xml/", secondary_proj_id, "?download=false&gzip=false") %>% GET(url = .) %>% content %>% as_list
  return(secondary_res$STUDY_SET$STUDY$IDENTIFIERS$SECONDARY_ID[[1]])
}

find_multiple_project_accession <- function(archive, accession_list) {
  print(accession_list)
  
  if (archive %in% c("SRA", "ENA")) {
  acc_vec <- str_split(accession_list, ",") %>% unlist
  proj_res <- map(acc_vec, find_project_accession) %>% unlist %>% unique
  return(paste0(proj_res, collapse = ","))
  } else {
    return("NOT_INDSC")
  }
}

#find_project_accession("SRS4625244")

## This workS!!!
ancient_metagenome <- read_tsv("ancientmetagenome-hostassociated/ancientmetagenome-hostassociated.tsv")
ancient_metagenome <- mutate(ancient_metagenome, archive_project_accession = map2(archive, archive_accession, find_multiple_project_accession))

ancient_singlegenome <- read_tsv("ancientsinglegenome-hostassociated/ancientsinglegenome-hostassociated.tsv")
ancient_singlegenome <- mutate(ancient_singlegenome, archive_project_accession = map2(archive, archive_accession, find_multiple_project_accession))

ancient_environmental <- read_tsv("ancientmetagenome-environmental/ancientmetagenome-environmental.tsv")
ancient_environmental <- mutate(ancient_environmental, archive_project_accession = map2(archive, archive_accession, find_multiple_project_accession))
```

At its core is the GET request against the ENA browser API. For all new accessions in a PR, maybe use a GET request (e.g. with CURL, or something within python) to check the accession exists in the database.

This maybe applicable to other services like MG-RAST etc.

**Comment by maxibor** [comment]
There are quite a few repositories used in AncientMetagenomeDir, so this is not a trivial one ;)

**Comment by jfy133** [comment]
My idea would primarily use just ENA/SRA as they consist of the majority of the data, anything else is unusual and would be up to the submitter to work out. Up to you though!

**Comment by maxibor** [comment]
Partial implementation here:

To extend further

https://github.com/SPAAM-community/AMDirT/blob/ff87211bb0a2b20cf06e45dce3b7791ddae4b600/AMDirT/filter/utils.py#L39

**Comment by jfy133** [comment]
Alternatively use REGEX: https://ena-docs.readthedocs.io/en/latest/submit/general-guide/accessions.html

**Comment by maxibor** [comment]
I let you update the JSON schema ;)

**Comment by jfy133** [comment]
The problem is that we have non-ENA stuff also, so it would have to be in test-dataset because you would only run it if you hhit a sample/library from the ENA/SRA. It's unfortunate with teh json schema we can't 'conditionally' check (although defeats the point, of course)

But again, can do it later :+1:
