### ISSUE TITLE
Can't launch viewer

### ISSUE THREAD

**Issue by plasmid02** [SPAAM-community/AMDirT#129]
I installed to a fresh conda environment on a new Miniconda installation on a Mac intel laptop

When I try to launch any command I get five lines of `"WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager"` 

Launching the viewer I get a long traceback

` You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.12.228:8501

2023-10-04 17:56:06.836 Uncaught app exception
Traceback (most recent call last):
  File "/Users/timothyread/miniconda/envs/amdirt/lib/python3.12/site-packages/streamlit/runtime/caching/storage/in_memory_cache_storage_wrapper.py", line 87, in get
    entry_bytes = self._read_from_mem_cache(key)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
`

etc etc

Any hints about how to proceed?  I guess its a streamline problem?

FWIW I pulled the biocontainer and tried to run using Docker but ended up at the same error messages when I tried the viewer

**Comment by jfy133** [comment]
Hi @plasmid02 

Could you please provide the exact method of installation?

I will see if I can replicate the error

**Comment by jfy133** [comment]
Hi @plasmid02 

Could you please provide the exact method of installation?

I will see if I can replicate the error

**Comment by jfy133** [comment]
Actually looking again, it seems the conda install has resolved to python version 3.12 which came out 3 days ago I think...

I wonder if we need to pin the version of python. I will test this later, although it doesn't explain the Biocontainer problem

**Comment by jfy133** [comment]
OK I've replicated the issue, and I have a suspicion, I'll see if I can fix it

**Comment by jfy133** [comment]
In the meantime the web app still appears to be working: https://www.spaam-community.org/AMDirT/

**Comment by plasmid02** [comment]
Yes it works! Thanks! Still getting the same warnings but same performance as the public web app

**Comment by jfy133** [comment]
:tada: Yes the warnings are something upstream in streamlit that haven't been resolved, but should not affect functionality :)
