### ISSUE TITLE
Add a button to download the actual table (sample metadata) selected in the viewer

### ISSUE THREAD

**Issue by ZoePochon** [SPAAM-community/AMDirT#131]
Hi there, 

This is not urgent and more about user experience, but it would be nice to add a button on AMDirT viewer to actually download the sample metadata table that one has selected and not only the corresponding library metadata table. Maybe it's me but I didn't find it. 

Great tool, by the way :-)

**Comment by jfy133** [comment]
Good idea! Should be pretty straight forward, right @maxibor ?

**Comment by jfy133** [comment]
I just noticed that Streamlit does this natively

![image](https://github.com/SPAAM-community/AMDirT/assets/17950287/630bf3d2-dfa5-4c7c-9729-3ef834962e97)

**Comment by maxibor** [comment]
On top of the native streamlit ag-grid export, there's now a button to download it  with #133
