### ISSUE TITLE
`AMDirT download` functionality to download AncientMetagenomeDir tables

### ISSUE THREAD

**Issue by jfy133** [SPAAM-community/AMDirT#146]
I was about to start writing a tutorial and I realised i'm going to have a to faff around with manually downloading tables before getting started on the tutorial.

What about a command called `AMDirT download` that allows you to specify

- `-table`: a given the Dir table 
- `--type`: whether samples or libraries
- `--version`: the release version

e.g.: `AMDirT download  --table ancientmetagenome-hostgenome --type samples --version 23.9.0`

And then you could have an almost reasonable end-to-end  CLI workflow:

```
AMDirT download  --table ancientmetagenome-hostgenome --type samples --version 23.9.0
grep <some filtering> ancientmetageome-hostgenome_samples.tsv > filtered.tsv
AMDirT convert --eager filtered.tsv ancientmetagenome-hostgenome
```

or w/e

One question would be should it pull this from a Zenodo archive (more stable) or GitHub (easier to puill with tags)

**Comment by maxibor** [comment]
Sounds like a good idea !

**Comment by maxibor** [comment]
Done with #149
