### ISSUE TITLE
Add 'convert' subtool

### ISSUE THREAD

**Issue by jfy133** [SPAAM-community/AMDirT#22]
This converts a (pre-filtered) AncientMetagenomeDir table to fetchngs/eager etc.

Basically re-uses the conversion from `download`, but allows someone to filter in their own tool rather than GUI

**Comment by jfy133** [comment]
This would also be useful for cli power users or people who work solely on headles sclusters :+1:

**Comment by maxibor** [comment]
Added with 4c2064c
