### ISSUE TITLE
Rename the tool

### ISSUE THREAD

**Issue by jfy133** [SPAAM-community/AMDirT#23]
ancientMetagenomeDirCheck is (rightly) a very clunky name, and restrictive to the functionality.

We should rename it to something more generic and easy to say.

According to this [slack poll](https://spaam-community.slack.com/archives/C0183TC8B0R/p1640093173208000), the most popular name is `amedirt` standing for **A**ncient **Me**tagenome **Dir** **T**oolkit.

I don't find it that descriptive personally, but I guess only people in the field would want to use it anyway, and in that case would know about it.

**Comment by maxibor** [comment]
rename to `AMDirT`: AncientMetagenomeDir Toolkit 🙂

**Comment by jfy133** [comment]
If you do'nt mind
