### ISSUE TITLE
Unecessary debugging code being printed to terminal during filter

### ISSUE THREAD

**Issue by jfy133** [SPAAM-community/AMDirT#25]
When pressing 'create eager table' from within the tool the following message gets printed to the terminal

![image](https://user-images.githubusercontent.com/17950287/147100602-4a3a707e-d33a-4ec9-ab11-9850159bd803.png)

Useful for debugging, but unecessary for the typical use. I would suggest either removing it or making a `--verbose` flag

**Comment by maxibor** [comment]
removed with 4c2064c
