### ISSUE TITLE
add ability to select all visible rows filter table

### ISSUE THREAD

**Issue by jfy133** [SPAAM-community/AMDirT#27]
![image](https://user-images.githubusercontent.com/17950287/147101643-ed40978e-33c8-4d64-8ad9-ea71a0ad3370.png)

Currently you have to tick one-by-one each of the rows you want to download. This would be sort of annoying if you wanted to select hundred(s) of samples.

**Comment by maxibor** [comment]
I tried to play with that, but it's unfortunately not as simple as the "select all" checkbox select also the non-visible rows (aka. also the non-filtered).
You can shift-click to extend selection though (will need a doc to explain all that)

**Comment by jfy133** [comment]
Mmm, this is a bit awkward then. I guess that means there is no possibility of a 'deslect all'? 

I tried the shift click thing but I accidently selceted the entire table.
