### ISSUE TITLE
Range filter excludes the specified search queries

### ISSUE THREAD

**Issue by jfy133** [SPAAM-community/AMDirT#28]
e.g. select ancientmetagenome-hostassociated

Filter publication years in range 2015-2018

Only years in 2016/2017 will be selected, 2015 and 2018 publications are not displayed.

**Comment by maxibor** [comment]
For integers, you have these 2 filtering options:
- `Less than/Greater than`
- `Less than or equals/Greater than or equals`

**Comment by jfy133** [comment]
Oops you're right - my bad
