### ISSUE TITLE
Also include library metadata information in the table for filtering

### ISSUE THREAD

**Issue by jfy133** [SPAAM-community/AMDirT#34]
This will contain additional useful information e.g. for whether single/paired, double/single stranded, udg treated or not etc.

**Comment by maxibor** [comment]
Could do, though we need to think about this, because it multiplies the lines of the table by the number of library designs for each sample that has different ones, which might be confusing...

**Comment by maxibor** [comment]
Issue to pair with #12

**Comment by maxibor** [comment]
Done with 8842113
