### ISSUE TITLE
Weird accession list results

### ISSUE THREAD

**Issue by jfy133** [SPAAM-community/AMDirT#36]
I found that I would get 

1. No accession IDs
    - Selecting hostassociated-metagenome table > filter material type to tooth > select just samples from SeguinOrlando2021 (no table generated)
2. Wierd accession list
    - Selecting hostassociated-metagenome table > filter material type to tooth > select oen sample from Brealey2020 & 4 from Neukam2020 [results in 4 tiimes the Brealey2020 ERS number]

**Comment by maxibor** [comment]
1. Because there are no library metadata available for SeguinOrlando2021 😉 
2. Because there are 4 libraries in the Brealey sample you selected, and no library metadata available for Neukam2020

**Comment by jfy133** [comment]
I realise now I wrote that issue in a complete rush and it was completely unclear

1. Sorry mistake for SeguinOrlando, it was meant to be the single-genome table. And there is library metadta: https://www.ebi.ac.uk/ena/browser/view/ERS5823072, but validation doesn't find anything.
2. For Brealey2020, the issue is that while indeed you have multiple libraries per sample (this makes sense for the eager table), but for tha fetchNGS list, you have multiple entries of the ERS same code (presumably corresponding to each library), but you don't want to download the same 4 libraries 4 times (for each duplicate).
3. Yup OK you're right - this confusion is derived from 2.

**Comment by maxibor** [comment]
1. The library metadata is not available in https://github.com/SPAAM-community/AncientMetagenomeDir/blob/dev/ancientsinglegenome-hostassociated/libraries/ancientsinglegenome-hostassociated_libraries.tsv so it's not able to create any table
2. I'm on it

**Comment by jfy133** [comment]
Sorry, must have confused sample and library metadata :facepalm:
