### ISSUE TITLE
Allow to specify which pipeline samplesheet TSV files to convert to

### ISSUE THREAD

**Issue by jfy133** [SPAAM-community/AMDirT#39]
Currently by default you will just create both eager  & fetchNGS, for future proofing this should be specifiable by the user.

e.g.

`--convert-to eager` or `--convert-to eager,fetchngs` or something

**Comment by maxibor** [comment]
Modify the click CLI with https://click.palletsprojects.com/en/8.1.x/options/#multiple-options
