### ISSUE TITLE
Add reporting version of the 'Dir release pulling from

### ISSUE THREAD

**Issue by jfy133** [SPAAM-community/AMDirT#43]
Given we are versioning this stuff, I think it would make sense to report which release we are pulling from (particularly given we allow retroactive modifyication of metadata fields with errors in them etc.).

Maybe even a dropdown menu allowing you to select which release based on GH release tags would work?

**Comment by maxibor** [comment]
Will do, but we first need a first release from the `dev` branch, as the structure of the dir from `master` is too different to be useful.

**Comment by jfy133** [comment]
It might even be useful to have a dropdown to select WHICH version of the dataset to use. This would then have to be inserted into `tables.json` (I guess?).

one sligtly tricky thing might be pointing towards what is the 'latest' release. If the ordering via version number doesn't work, we could consider setting up a `latest` tag: https://github.com/marketplace/actions/latest-tag

**Comment by jfy133** [comment]
.e.g by calling: curl -v "https://api.github.com/repos/spaam-community/AncientMetagenomeDir/tags"

**Comment by maxibor** [comment]
This should be fetched from the json file describing the tables: 

https://github.com/maxibor/AMDirT/blob/dev/AMDirT/assets/tables.json

**Comment by maxibor** [comment]
Done with 0a5169c4f525765bf2b6118ae0d536c8767a27e8
