### ISSUE TITLE
Mixing content-types of column causes entire column to fail

### ISSUE THREAD

**Issue by jfy133** [SPAAM-community/AMDirT#57]
@maxibor and I worked out that when you have a numeric column, but someone adds strings somewhere in there, on loading of the TSV file into the tool it will try to 'guess' the column content type and in this case forced everything to change to text type. Therefore all numeric values in the entire column were suddenly 'failing'.

This is a problem when very long tables means the error prints an error for EVERY LINE of that column which is sometimes too much for the error message.

It would be nice if we could find a way to force the column types, but not leave 'junk' content if the TSV tool replaces values when forcing.

I.e. the tool should fail with a single error message saying the column formatting is broken, rather than still printing every row.

**Comment by maxibor** [comment]
Getting the column type from the JSON schema in combination with the `dype` argument of `read_csv` should do the trick.
https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html

**Comment by jfy133** [comment]
Reproducible example here: https://github.com/SPAAM-community/AncientMetagenomeDir/pull/981

Where the `read_count` column had in the new submission fields commas e.g.: `123,000,000` rather than just `1230000000`

**Comment by ilight1542** [comment]
Heya, just wondering how we would want to deal with columns which do in fact accept 2 different types (eg either <class 'str'> as "NA" or <class 'int'> as 1234567 for column read_count)

alternatively a blank value (eg entry is empty between two tabs) could be a better solution (albeit less readable in the tsv form)

dtype can only case 1 to 1


related: the fix I am trying to get working for the initial parsing of the dataset into a pandas array now breaks if a numeric column has a scientific notation for what should be numeric (eg  """Slon2017        2017    10.1126/science.aam9695 SP3844  ENA     PRJEB18629      ERS1600724      R9959   single  Herculase II Fusion DNA  none    1,681E+11       Illumina HiSeq 2500     PAIRED  WGS """). should all values be forced to be in standard notation?

**Comment by ilight1542** [comment]
https://pandas.pydata.org/pandas-docs/stable/user_guide/integer_na.html

**Comment by ilight1542** [comment]
opened pr #94

**Comment by jfy133** [comment]
Will be fixed in theDir in the 23.03 release!
