### ISSUE TITLE
No obvious way to clear selection of table

### ISSUE THREAD

**Issue by jfy133** [SPAAM-community/AMDirT#78]
i.e., make a selection, download the file, press 'reset app', then filter for different samples, but when you press the `download file` again, it holds the samples from the original selection.

We should either document you must manually unselect everything before deleting, or find out a way of the `grid` interface to display an unselect everything optio

**Comment by maxibor** [comment]
The all select/deselect button has been added with 49465f046db9706bd14d43f7ed9e5b291b5c51c5

**Comment by maxibor** [comment]
Sorry @julienfumey ,
An update of the streamlit-aggrid library which is used to render the tables has made this issue very trivial, hence it's now less relevant

**Comment by jfy133** [comment]
I think the select/deselect in the latest version of streamlit works, as does the new button name in #93
