### ISSUE TITLE
Create samplesheet input file for nf-core/mag

### ISSUE THREAD

**Issue by rozwalak** [SPAAM-community/AMDirT#82]
What do you think about including another functionality to create samplesheet input file for nf-core/mag?

**Comment by jfy133** [comment]
yes good idea!

**Comment by maxibor** [comment]
Currently, the [input sheet of nf-core/mag](https://nf-co.re/mag/2.2.1/usage) should look like this 

| sample  	| group 	| short_reads_1            	| short_reads_2            	| long_reads            	|
|---------	|-------	|--------------------------	|--------------------------	|-----------------------	|
| sample1 	| 0     	| data/sample1_R1.fastq.gz 	| data/sample1_R2.fastq.gz 	| data/sample1.fastq.gz 	|
| sample2 	| 0     	| data/sample2_R1.fastq.gz 	| data/sample2_R2.fastq.gz 	| data/sample2.fastq.gz 	|
| sample3 	| 1     	| data/sample3_R1.fastq.gz 	| data/sample3_R2.fastq.gz 	|                       	|

Maybe we should we put the runs as samples, and assign the same group to runs coming from the same acual sample

**Comment by rozwalak** [comment]
It should be a good solution, I think
