### ISSUE TITLE
Select all check box absent in column

### ISSUE THREAD

**Issue by mlo89** [SPAAM-community/AMDirT#88]
When I want to select all the samples directly in one column (not filtering the view) I have to group them by e.g. year then I check all the boxes of the years and then expand the selection. When I expand the selection I notice that there is a "select all" check box per each year (very useful indeed). However, would it be possible to have the "select all" check box for each column at the very beginning?

**Comment by maxibor** [comment]
Has been added 49465f046db9706bd14d43f7ed9e5b291b5c51c5
